image_folder: '/home/gpuadmin/dataset/test/output_product_crop'
workers: 4
batch_size: 192
saved_model: '/home/gpuadmin/2020811010/augmentation_test_backup/Recognition/best_accuracy.pth'
batch_max_length: 25
imgH: 32
imgW: 100
character: '0123456789abcdefghijklmnopqrstuvwxyz'
sensitive: True
PAD: False
Transformation: 'TPS'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'Attn'
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
rgb: False